### ISSUE TITLE
No module named 'prefetch_generator'

### ISSUE THREAD

**Issue by zuzi2015** [mj129/CoANet#7]
运行test.py的时候出现错误
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    from dataloaders import custom_transforms as tr
  File "/data0/wangxue/CoANet-main/dataloaders/__init__.py", line 3, in <module>
    from prefetch_generator import BackgroundGenerator
ModuleNotFoundError: No module named 'prefetch_generator'

**Comment by ParadiseEverlost** [comment]
同样报错。

**Comment by mj129** [comment]
You can install the dependency using "pip install prefetch_generator".
